reviews:
  auto_review: true
  review_status: true
  high_level_summary: true
  patch_notes: true
  suggestions: true
  code_issues: true

summaries:
  high_level: true
  concise: true

comments:
  enable_review_comments: true
  line_comments: true
